### PR TITLE
Gym v26 Migration

### PR DESCRIPTION
**Pull request by JacopoPan**
As per [this link](https://gymnasium.farama.org/content/migration-guide/) and requested in #133:

This PR will include changes migrating/supporting from **v21**

```python
import gym
env = gym.make("LunarLander-v2", options={})
env.seed(123)
observation = env.reset()

done = False
while not done:
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, done, info = env.step(action)

    env.render(mode="human")

env.close()
```

to **v26**

```python
import gym
env = gym.make("LunarLander-v2", render_mode="human")
observation, info = env.reset(seed=123, options={})

done = False
while not done:
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    done = terminated or truncated

env.close()
```

### CODE REVIEW

**Comment by JacopoPan** [comment]
@paehal

see
https://github.com/utiasDSL/gym-pybullet-drones/blob/6bab1f6a319833a3b7441b1baae39dd0e13244f3/gym_pybullet_drones/envs/BaseAviary.py#L225-L239

and 
https://github.com/utiasDSL/gym-pybullet-drones/blob/6bab1f6a319833a3b7441b1baae39dd0e13244f3/gym_pybullet_drones/envs/BaseAviary.py#L252-L282

The suggestions from [this page](https://gymnasium.farama.org/content/migration-guide/) are to fix the `step()` method (in `BaseAviary.py`) simply by
> replacing done with terminated and truncated=False in [step()](https://gymnasium.farama.org/api/env/#gymnasium.Env.step)

The `info` dictionary returned by `step()` in `BaseAviary` is computed in method `_computeInfo()` (which is not really doing anything in the current implementation other than returning empty dictionaries for each drone)
https://github.com/utiasDSL/gym-pybullet-drones/blob/3fc246f26b99e61e03ccc8be5dfa8b9843b5edfa/gym_pybullet_drones/envs/multi_agent_rl/LeaderFollowerAviary.py#L109-L120
You could simply used that to create the additional return for `reset()` as well

**Comment by JacopoPan** [comment]
@paehal

let me know if you want to open a separate PR on a fork of yours for this (or if you want to be added as a collaborator to push to this branch specifically)

**Comment by paehal** [comment]
@JacopoPan 
Thanks for taking notes on all of this.
I would like to work on this modification as well.
I am following the procedure and making the changes, but I need advice on reset section.

Even if the return value of reset can return both obs and info as shown below, I get the following error. 
What should I do?
################################################################

`    def reset(self, *, seed=None, options=None):
        """Resets the environment.
        ~~~~~~~~
        **_return ([self._computeObs(), self._computeInfo()])_**`


Error Message
`_self.last_obs, self.last_infos = obs_and_infos
ValueError: too many values to unpack (expected 2)_`




_I'm not very familiar with github, so please point out any misbehavior._

**Comment by JacopoPan** [comment]
Could you make a [make a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) with the modification you made to the `reset()` method?

**Comment by paehal** [comment]
@JacopoPan 

I have made a pull request for the reset and step functions.

I am still getting other errors and am stuck on "policy_mapping_fn". 
Do you have any assumptions as to the cause of the error?

`ray/rllib/evaluation/episode_v2.py", line 120, in policy_for policy_id = self._agent_to_policy[agent_id] = self.policy_mapping_fn( TypeError: <lambda>() got an unexpected keyword argument 'worker'`

**Comment by JacopoPan** [comment]
Can you show me the complete error log to know from where in `gym-pybullet-drones` this is triggered in `ray`?

**Comment by paehal** [comment]
@JacopoPan 

The following is the difference between the error content in the logs when it is working well and when it is failing this time.
Judging from the error contents, I think the change of ray has an effect.

  File "<package install directory>site-packages/ray/tune/trainable/trainable.py", line 368, in train
    raise skipped from exception_cause(skipped)
  File "<package install directory>site-packages/ray/tune/trainable/trainable.py", line 365, in train
    result = self.step()
  File "<package install directory>site-packages/ray/rllib/algorithms/algorithm.py", line 782, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "<package install directory>site-packages/ray/rllib/algorithms/algorithm.py", line 2713, in _run_one_training_iteration
    results = self.training_step()
  File "<package install directory>site-packages/ray/rllib/algorithms/dqn/dqn.py", line 405, in training_step
    new_sample_batch = synchronous_parallel_sample(
  File "<package install directory>site-packages/ray/rllib/execution/rollout_ops.py", line 82, in synchronous_parallel_sample
    sample_batches = [worker_set.local_worker().sample()]
  File "<package install directory>site-packages/ray/rllib/evaluation/rollout_worker.py", line 914, in sample
    batches = [self.input_reader.next()]
  File "<package install directory>site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "<package install directory>site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "<package install directory>site-packages/ray/rllib/evaluation/env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "<package install directory>site-packages/ray/rllib/evaluation/env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "<package install directory>site-packages/ray/rllib/evaluation/env_runner_v2.py", line 515, in _process_observations
    policy_id: PolicyID = episode.policy_for(agent_id)
  File "<package install directory>site-packages/ray/rllib/evaluation/episode_v2.py", line 120, in policy_for
    policy_id = self._agent_to_policy[agent_id] = self.policy_mapping_fn(
TypeError: <lambda>() got an unexpected keyword argument 'worker'

Incidentally, changing the following part of multiagent.py changed the error content, so it may be related to this part.

` "policy_mapping_fn": lambda x: "pol0" if x == 0 else "pol1", # # Function mapping agent ids to policy ids`

**Comment by JacopoPan** [comment]
Everything you posted there however starts from `site-packages/ray/`, can you go back into the terminal printouts until the line in `multiagent.py` where this starts (which I believe is the one you posted, but all errors from that point on could be relevant). Let's continue in #136

**Comment by paehal** [comment]
>Everything you posted there however starts from site-packages/ray/, can you go back into the terminal printouts until the line in multiagent.py where this starts (which I believe is the one you posted, but all errors from that point on could be relevant). Let's continue in [#136](https://github.com/utiasDSL/gym-pybullet-drones/pull/136)

Among the output in the terminal when executed on the server, the error related to `multiagent~.py` appears at the end. The error I indicated appears before that, is that strange?

The error related to multiagent~.py is something like this, and I often see this error message when the computation is not working well for reasons other than this.

  `File "experiments/learning/“_my_original_multiagent_file_”.py", line 712, in <module>
    results = tune.run(
  File “***/python3.8/site-packages/ray/tune/tune.py", line 792, in run
    raise TuneError("Trials did not complete", incomplete_trials)`

**Pull request closed without merging**
