### PR TITLE
change step and reset function for ray2.3

### PR DESCRIPTION
**Pull request by paehal**
I have made my changes to the reset and step functions according to https://gymnasium.farama.org/content/migration-guide/.

However, the error still remains and is as follows

`ray/rllib/evaluation/episode_v2.py", line 120, in policy_for
    policy_id = self._agent_to_policy[agent_id] = self.policy_mapping_fn(
TypeError: <lambda>() got an unexpected keyword argument 'worker'`

Probably, 

multiagent.py
        '"policy_mapping_fn": lambda x: "pol0" if x == 0 else "pol1", # # Function mapping agent ids to policy ids'

I think it has something to do with...

### CODE REVIEW

**Review by JacopoPan — CHANGES_REQUESTED** [review]
The original package was developed tested with Ray 1.9, not 2.2, could you make that explicit in the commented out lines?

**Comment by paehal** [comment]
>Everything you posted there however starts from site-packages/ray/, can you go back into the terminal printouts until the line in multiagent.py where this starts (which I believe is the one you posted, but all errors from that point on could be relevant). Let's continue in https://github.com/utiasDSL/gym-pybullet-drones/pull/136

Among the output in the terminal when executed on the server, the error related to `multiagent~.py` appears at the end. The error I indicated(about policy_mapping_fn) appears before that, is that strange?

The error related to `multiagent~.py` is something like this, and I often see this error message when the computation is not working well for reasons other than this.

`File "experiments/learning/“_my_original_multiagent_file_”.py", line 712, in <module> results = tune.run( File “***/python3.8/site-packages/ray/tune/tune.py", line 792, in run raise TuneError("Trials did not complete", incomplete_trials)`

**Comment by JacopoPan** [comment]
> > Everything you posted there however starts from site-packages/ray/, can you go back into the terminal printouts until the line in multiagent.py where this starts (which I believe is the one you posted, but all errors from that point on could be relevant). Let's continue in #136
> 
> Among the output in the terminal when executed on the server, the error related to `multiagent~.py` appears at the end. The error I indicated(about policy_mapping_fn) appears before that, is that strange?
> 
> The error related to `multiagent~.py` is something like this, and I often see this error message when the computation is not working well for reasons other than this.
> 
> `File "experiments/learning/“_my_original_multiagent_file_”.py", line 712, in <module> results = tune.run( File “***/python3.8/site-packages/ray/tune/tune.py", line 792, in run raise TuneError("Trials did not complete", incomplete_trials)`

Can you post the _entire_ terminal output? (You can change the settings of you terminal to allow infinite or very large scroll back if that is an issue)

Also, try to use a block starting with ```sh on one separate line
Then your output
And the ending with another 3 ` on another line, to create

```sh
Output
Output
Output
```

**Comment by JacopoPan** [comment]
Closed as superseded by #138

**Pull request closed without merging**
