### PR TITLE
Implemented the desired scenario of the ownship

### PR DESCRIPTION
**Pull request by amaalo2**
Hi Jacopo, 

Can you please take a look at this? I think my scenario works but I am having trouble with randomizing the goal after every reset.

### CODE REVIEW

**Comment by JacopoPan** [comment]
I'll have a look, I'd say that the best place to randomize something at the beginning of each episode is the housekeeping methods
https://github.com/utiasDSL/gym-pybullet-drones/blob/fd3a0d839f1019f4cb14e208b2a6bf886e78cb36/gym_pybullet_drones/envs/BaseAviary.py#L450
which is called by both `__init__()` and `reset()` in `BaseAviary`

**Comment by JacopoPan** [comment]
I didn't run it but I quickly read your code @amaalo2, I think you changed all the relevant points.
One thing I would have tried is to run a controlled example of your new `VelocityAviary` before plugging it into `stable-baselines3`.
I cannot tell whether what you are doing with the intruders' scripted actions the the reward/done is exactly what you have in mind or the best way to do it but, on a quick look, they seem reasonable.

You observation contains information about the own ship and the relative position/velocity from the intruder/goal.
You reward is based only on the distance from the goal. Your done conditions are based on collisions, reaching the goal, timeout.

I would have 2 comments about the RL problem: the current formulation might incentivize reaching the goal more slowly to collect more reward; the -inf, +inf bounds for the observation space might make the problem quite difficult, I'd try to add some bounds (and including them as conditions to terminate an episode).

**Comment by amaalo2** [comment]
So prior to plugging the results in `stable-baselines3`  I did test a deterministic scenario where I simulated a head-on collision, and ownship and the intruder behaved as expected.

I updated my observation space bounds to be limited.

```
        #observation vector           x         y     z         vx      vy       vz       relx    rely     relz     relvx    relvy    relvx  distance ownship to intruder     dist2goal
        obs_lower_bound = np.array([-10.,       -10.,   0.,   -10,       -10,     -10,    -10,       -10,      -10,   -10,       -10,      -10,    0.,                               0.])
        obs_upper_bound = np.array([ 10.,        10.,   20.,   10,        10,      10,     10,        10,       10,    10,        10,       10,    20,                              20])
 
```

I've trained by training this agent, I noticed a few issues:

1. The agent keeps on yawing, so I updated the reward function to penalize yaw angle by the yaw angle amount.
2. When I kept the `1/doi` in the penalty term, after 10 m steps, the agent kept speeding up towards the ground. I removed the penalty. 
3. I also added reward for proportional to the x component of the velocity because I want to incentivize my drone to go forward. 

```
reward =  10*self.pos[0,0]/np.linalg.norm(self.pos[0,:])  - np.abs(self.rpy[0, 2]) + 10/d2g #- 1 /doi
```

Would you have any suggestions for the RL problem statement or a crafting the reward function?

**Comment by JacopoPan** [comment]
I think you did good in checking a non-learning scenario first!

I think then now much of your work will be about handcrafting the reward function/done conditions.
General comments are that a dense reward and some early termination done conditions for undesirable behaviour might make learning a bit easier.

Also, your action and observations spaces are still large, so consider using a custom number of layers and nodes in your networks.

**Pull request closed without merging**
