### PR TITLE
[Fix Bug] fix small bug in test_multiagent.py

### PR DESCRIPTION
**Pull request by hany606**
- Change actions that passed to env.step() to include actions for all agents

## Previously

There are only 2 policies in experiments/learning/multiagent.py to be trained

https://github.com/utiasDSL/gym-pybullet-drones/blob/333ec90219bd39fe69aad53734a21f27faf2449b/experiments/learning/multiagent.py#L269-L273

There are only 2 policies imported from the trained agent and the dictionary that is passed for env.step stores actions only for 2 drones.

https://github.com/utiasDSL/gym-pybullet-drones/blob/333ec90219bd39fe69aad53734a21f27faf2449b/experiments/learning/test_multiagent.py#L265-L271

https://github.com/utiasDSL/gym-pybullet-drones/blob/333ec90219bd39fe69aad53734a21f27faf2449b/experiments/learning/test_multiagent.py#L319-L323

## Now

The same 2 policies imported and only the actions are passed for all the agents.

https://github.com/hany606/gym-pybullet-drones/blob/fe1b1a47eb451f0d6b972bb2eb7c8e09fafb66df/experiments/learning/test_multiagent.py#L319-L325

## Next
This fix works perfect for leader and follower environment but not on other environments I believe, as we have multiple agents and each agent can have a different policy, but I am not sure if it was an intention only to implement it like this or not. Thus, in another pull-request or a continuation for this pull-request, I can change the implementation of experiments/learning/multiagent.py to train a policy for each agent.

At the end, thank you very much for your simulator, it is great and really amazing documentation!

### CODE REVIEW

**Comment by JacopoPan** [comment]
Hi @hany606,

you are correct in pointing out that the current implementation of `multiagent.py` is only meant for 2 agents (and demonstrated with the Leader-Follower environment). Generalization to the N-agents scenario is something I'd left for later this spring (because it would also require to re-write the classes and functions for the centralized critics).

If it's something you are interested in developing in this PR, I would encourage to do so! (Maybe I would still add/change the implementation myself rather than merging from PR but I can have you appear as contributor regardless, if you want.)

**Comment by hany606** [comment]
> If it's something you are interested in developing in this PR, I would encourage to do so! (Maybe I would still add/change the implementation myself rather than merging from PR but I can have you appear as contributor regardless, if you want.)

I will try to work on developing it as it collides with my goals for using this environment, maybe you can guide me for which files and classes that I might look on to change.
As you want, it is totally fine with me.

**Comment by JacopoPan** [comment]
All that code that would need revision is
https://github.com/utiasDSL/gym-pybullet-drones/blob/333ec90219bd39fe69aad53734a21f27faf2449b/experiments/learning/multiagent.py#L1
and
https://github.com/utiasDSL/gym-pybullet-drones/blob/333ec90219bd39fe69aad53734a21f27faf2449b/experiments/learning/test_multiagent.py#L1
and they aren't big files, they also contain quite a bit of duplicated code that would be nice to factor out but it relies on run-time constants so it's not too straightforward without circular dependencies (I need to re-think it a bit)

The main point is that the centralized critic requires a special observation whose size depend on the number of UAVs in the team. Are you planning on using a centralized critic in your work? Because if you do not, the scripts above could and should be simplified.

**Comment by hany606** [comment]
> and they aren't big files, they also contain quite a bit of duplicated code that would be nice to factor out but it relies on run-time constants so it's not too straightforward without circular dependencies (I need to re-think it a bit)

Ok that's great, I will check them and I will try my best in solving it and refactor the code.

> The main point is that the centralized critic requires a special observation whose size depend on the number of UAVs in the team. Are you planning on using a centralized critic in your work? Because if you do not, the scripts above could and should be simplified.

Currently, I am new for multi-agent RL, so I am not sure to use a centralized critic or not for my work, but I will read the literature and maybe try. If you can suggest interesting papers to read, it will be great!

**Comment by JacopoPan** [comment]
Sounds good! I guess the *very famous* papers include MADDPG and QMIX but, if I was you, I'd start by looking at practical implementations (e.g., in [RLlib](https://docs.ray.io/en/latest/rllib-algorithms.html)) rather than the publications themselves. The papers can give you the high-level idea but there are always quirks and details and fixes, etc. that go into actual code bases.

**Comment by hany606** [comment]
Great, thank you very much, I will definitely take your advice! :smiley:

**Comment by JacopoPan** [comment]
:+1: note how `multiagent.py` is based on the [shared critic example](https://docs.ray.io/en/latest/rllib-algorithms.html#shared-critic-methods) from the various [MARL methods](https://docs.ray.io/en/latest/rllib-algorithms.html#multi-agent-methods) presented in RLlib's docs

**Pull request closed without merging**
